baseurl: "https://tillbey.github.io/travis-test/"
# theme: "hugo-bootstrap-premium"
metaDataFormat: "yaml"
# sectionPagesMenu: "main"


menu:
     main:
        name: "Github"
        weight: 2
        identifier: "github"
        URL: https://github.com/tillbey/travis-test
