baseurl: "https://tillbey.github.io/travis-test/"
# theme: "hugo-bootstrap-premium"
metaDataFormat: yaml
canonifyURLs: true

ouputs:
  page:
    - HTML
    - JSON

# outputFormats:
#   - JSON:
#     - path: snip
