baseurl: "https://tillbey.github.io/travis-test/"
# theme: "hugo-bootstrap-premium"
metaDataFormat: yaml
sectionPagesMenu: main

menu:
     main:
      - name: "Downloads"
        weight: 5
        identifier: "downloads"
        URL: /downloads
      - name: "Documentation"
        weight: 5
        identifier: "docs"
        URL: /docs
      - name: "Pipelines"
        identifier: pipelines
        weight: 4
        URL: /pipelines
      - name: "Blog"
        identifier: "posts"
        weight: 3
        URL: /posts
      - name: "s"
        identifier: "search"
        weight: 2
        URL: /search
      - name: "Github"
        identifier: "github"
        weight: 1
        URL: https://github.com/tillbey/travis-test
